language: scala

jdk:
    - openjdk11

scala:
    - 2.12.10

script:
    - sbt ++$TRAVIS_SCALA_VERSION scalastyle scripted

before_cache:
    - rm -fv $HOME/.ivy2/.sbt.ivy.lock
    - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
    - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
    directories:
        - $HOME/.cache/coursier
        - $HOME/.ivy2/cache
        - $HOME/.sbt
